# Generated by Django 3.2 on 2025-04-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', 'add_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
