# Generated by Django 3.2 on 2025-04-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='author_application_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credentials',
            field=models.TextField(blank=True, help_text='Образование, сертификаты и опыт'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expertise_areas',
            field=models.ManyToManyField(blank=True, related_name='experts', to='main.ExpertiseArea'),
        ),
    ]
