# Generated by Django 3.2 on 2025-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250406_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credentials',
            field=models.TextField(blank=True, help_text='Education, certificates and experience'),
        ),
    ]
