# Generated by Django 3.2 on 2025-04-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250409_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identification',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
