# Generated by Django 3.2 on 2025-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250409_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identification',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
